### ISSUE TITLE
Add Shelter Field to Application Model

### ISSUE THREAD

**Issue by iamyanbo** [lujorryn/PetPal-G0346#2]
Since a shelter should be able to see their list of applications from users, the PetPalUser should also have a field for seeker, this way we can filter efficiently.

**Comment by lujorryn** [comment]
Not entirely sure that I see the purpose of this, can you elaborate a little more on what scenario/workflow would we need this field?

**Comment by iamyanbo** [comment]
Sorry typo I meant Application model

**Comment by lujorryn** [comment]
I see now, then yes I agree that would be helpful, thanks for the catch. 
Btw since I created classes for Shelter and Seeker now, we can use ForeignKey(Shelter) and ForeignKey(Seeker) to refer to shelter/seeker specific relations, but I'll leave that up to everyone to change to how they see fit.

**Comment by iamyanbo** [comment]
Is the PetPalUser with role not a thing anymore?

**Comment by lujorryn** [comment]
If you look at [models.py](https://github.com/lujorryn/PetPal-G0346/blob/main/petpal/accounts/models.py) of the account app right now, you can see that Shelter and Seeker are "subclasses" (not sure if subclass is the correct term) queried from PetPalUser based on the role field of PetPalUser, so it is still a thing, but now you can directly fish stuff out of Shelters and Seekers by calling Shelter and Seeker.
[Here](https://github.com/lujorryn/PetPal-G0346/blob/main/petpal/accounts/management/commands/createusers.py#L11-L13) is a small example of how you use these "subclasses"
https://github.com/lujorryn/PetPal-G0346/blob/3e7689338801cd3a11a272ef18be77df0454bd96/petpal/accounts/management/commands/createusers.py#L11-L13
